# Generated by Django 5.1.5 on 2025-05-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('kraj', models.CharField(default='Międzynarodowa', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('date_and_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze', to='liga_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('wiek', models.IntegerField(blank=True, null=True)),
                ('narodowosc', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gracze', to='liga_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuta', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gole', to='liga_app.game')),
                ('strzelec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gole', to='liga_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminarz', to='liga_app.league')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze', to='liga_app.schedule'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('miasto', models.CharField(blank=True, max_length=255, null=True)),
                ('zalozony', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zespoly', to='liga_app.league')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='zespoly',
            field=models.ManyToManyField(related_name='gracze', to='liga_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='gosc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gosc_mecze', to='liga_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='gospodarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gospodarz_mecze', to='liga_app.team'),
        ),
        migrations.CreateModel(
            name='Wynik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gole_gospodarz', models.IntegerField(default=0)),
                ('gole_gosc', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wynik', to='liga_app.game')),
            ],
        ),
    ]
