# Generated by Django 5.1.5 on 2025-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pozycja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
