# Generated by Django 5.1.5 on 2025-05-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_app', '0002_player_pozycja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='kraj',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='narodowosc',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pozycja',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wiek',
        ),
        migrations.RemoveField(
            model_name='team',
            name='miasto',
        ),
        migrations.RemoveField(
            model_name='team',
            name='zalozony',
        ),
        migrations.AlterField(
            model_name='game',
            name='gosc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_gosc', to='liga_app.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gospodarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_gospodarz', to='liga_app.team'),
        ),
    ]
